### ISSUE TITLE
is this still working?

### ISSUE THREAD

**Issue by qiusli** [gabrieltheodoropoulos/EmailComposer-Xcode12#1]
trying to use it in XCode 13 and iOS 15, it always shows the view saying unable to send emails from this device either in preview or simulator. Did I miss anything?

**Comment by gabrieltheodoropoulos** [comment]
Hi @qiusli,

This repo contains a Swift package targeted to Xcode 12 only. To use EmailComposer package in Xcode 13 please take a look at [this repo](https://github.com/gabrieltheodoropoulos/EmailComposer.git). It's pretty much the same, but it's made for Xcode 13 and above as it makes use of Swift tools v5.5. Please see the description of this repository.

Also, you need a real device in order to try out email sending. Neither in the simulator, nor in a preview you'll ever manage to test if it's working or not. And yes, the message you get is normal.

If you want to read more about the email composer in general, please take a look [here](https://serialcoder.dev/text-tutorials/ios-tutorials/email-composer-on-ios/). If you'd like to find out the implementation steps of the EmailComposer in this package, then check out [this article](https://serialcoder.dev/text-tutorials/swiftui/composing-emails-in-swiftui-using-a-view-modifier/).

Hope I've helped!

**Comment by qiusli** [comment]
tyvm!
